=== JamesSkemp/PsnTrophies/PlayStationGame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="PlayStationGame">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Game">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Id"/>
							<xs:element name="IdEurope"/>
							<xs:element name="Title"/>
							<xs:element name="Image"/>
							<xs:element name="TrophiesCount">
								<xs:complexType>
									<xs:attribute name="Total" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Bronze" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Silver" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Gold" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Platinum" type="xs:nonNegativeInteger"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalPoints"/>
							<xs:element name="Platform"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Trophies">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="Trophy">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Id"/>
										<xs:element name="GameId"/>
										<xs:element name="Title"/>
										<xs:element name="Image"/>
										<xs:element name="Description"/>
										<xs:element name="Type"/>
										<xs:element name="Hidden" nillable="true" type="xs:boolean">
											<xs:annotation>
												<xs:documentation>Whether the trophy is hidden/secret.</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/PsnTrophies/games/NPWR03160_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR03160_00</Id>
    <IdEurope></IdEurope>
    <Title>Pinball Arcade</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/65225787556359B208075023B766A60D9381B5E9.PNG</Image>
    <TrophiesCount Total="12" Bronze="4" Silver="8" Gold="0" Platinum="0" />
    <TotalPoints>300</TotalPoints>
    <Platform>?</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Tales High 5</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/CF1C92916F979D0B3315C7747BFB1A373272233C.PNG</Image>
      <Description>Achieve a top 5 local high score on Tales of the Arabian Nights®</Description>
      <Type>BRONZE</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Tales Master</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/82CE689414986B3CE7F0B6CE2C57CF7F61427B67.PNG</Image>
      <Description>Complete the Standard Goals on Tales of the Arabian Nights®</Description>
      <Type>SILVER</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Tales Wizard</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/333AF35AFFC24CBA8DF3FAE1B8A3DABB7DE0A530.PNG</Image>
      <Description>Complete the Wizard Goals on Tales of the Arabian Nights®</Description>
      <Type>SILVER</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Ripley's High 5</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/F51869E89576AB87040B8C32387867C655F9D391.PNG</Image>
      <Description>Achieve a top 5 local high score on Ripley’s Believe it or Not!®</Description>
      <Type>BRONZE</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Ripley's Master</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/6CB11B87A46BD1D9C5CD6EAA6DE4F31735DAE7EB.PNG</Image>
      <Description>Complete the Standard Goals on Ripley’s Believe it or Not!®</Description>
      <Type>SILVER</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Ripley's Wizard</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/E34868261B83259C5FDDE6AA4487C4BF76BA5C27.PNG</Image>
      <Description>Complete the Wizard Goals on Ripley’s Believe it or Not!®</Description>
      <Type>SILVER</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Theatre High 5</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/481E1490808CCBA88C8B6990886DEFC28BA17AC1.PNG</Image>
      <Description>Achieve a top 5 local high score on Theatre of Magic®</Description>
      <Type>BRONZE</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Theatre Master</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/033D95054122C6A2B93B5ECD08FA6970770DD845.PNG</Image>
      <Description>Complete the Standard Goals on Theatre of Magic®</Description>
      <Type>SILVER</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Theatre Wizard</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/1F2EDAEF314FCD678125AAEC84EE80CE06FFE113.PNG</Image>
      <Description>Complete the Wizard Goals on Theatre of Magic® </Description>
      <Type>SILVER</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Black Hole High 5</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/44881B674FBE7F839185D42941CF947A38163644.PNG</Image>
      <Description>Achieve a top 5 local high score on Black Hole™</Description>
      <Type>BRONZE</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Black Hole Master</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/DA709B22F99A4960D197D7F7054E2D481E28658C.PNG</Image>
      <Description>Complete the Standard Goals on Black Hole™</Description>
      <Type>SILVER</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR03160_00</GameId>
      <Title>Black Hole Wizard</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03160_00_14688FF02E3D5F775783097C716EE6A054A713FE/3AC2F27710CD5C50B154A51636DD0FA559C5746A.PNG</Image>
      <Description>Complete the Wizard Goals on Black Hole™</Description>
      <Type>SILVER</Type>
      <Hidden>true</Hidden>
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/_wip/xXREDXIIIXx/NPWR04182_00.xml
<?xml version="1.0" encoding="UTF-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR04182_00</Id>
    <IdEurope/>
    <Title>Star Wars Pinball</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/051FFC7C5DA567D496A5F396E2BF4E3345F2A48A.PNG</Image>
    <TrophiesCount Total="19" Bronze="14" Silver="3" Gold="2" Platinum="0"/>
    <TotalPoints/>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Galactic explorer</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/A5FAEE7A260D0FE8DCEC094C5007340696FFFA75.PNG</Image>
      <Description>Discover your collection, and play on...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>The Force is...</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/372DCF809B58FDB86EA885F652D591EC84D90799.PNG</Image>
      <Description>Advance a rank and become a Jedi...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Fruitful alliance</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/91666F35C918C30EF5250E5C7888D2299C839E63.PNG</Image>
      <Description>Get your friends together and earn...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Master of the Force</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/4C4D0CD35FE52758A2A2C0E702BB87A9F77E93AA.PNG</Image>
      <Description>Have the highest Force Score among...</Description>
      <Type>GOLD</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Great Disturbance</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/DD144F440B67B000B7CB351FE9EEF8FAA7855CB4.PNG</Image>
      <Description>Keep playing hard, and earn a score...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Tremor in the Force</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/B6F75684CEFD98A2C61404DA5164248894961C1F.PNG</Image>
      <Description>Feel the Force and show off your...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Young Challenger</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/064088D795D66B5D3EFB8CC6533BCD9CAE913AD1.PNG</Image>
      <Description>Rise to the challenge and beat the...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Your powers are weak</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/39F4189C4DB40BF13BC7E1266647EE34919E20FC.PNG</Image>
      <Description>Dominate your friends and beat ten of...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Unstoppable menace</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/6D1ED5E0B0D0781C8A45CB285C947E9E68B61EE1.PNG</Image>
      <Description>Win an Online Multiplayer race...</Description>
      <Type>GOLD</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>It all ran better...</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/C5E768C56C60D74CA1080490AF19B135D7FEC89B.PNG</Image>
      <Description>Complete all of the Empire's special...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>In the service of...</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/232D5895EB409AFC7B7991F47F6E55D36DD2E22C.PNG</Image>
      <Description>Complete all of the Hutt Cartel's...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>13</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Triumph of the...</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/7875EF265BF2F145BA106E4936757FE89DD47309.PNG</Image>
      <Description>Earn maximum respect, and escape from...</Description>
      <Type>SILVER</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>14</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Go for the legs</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/D9F5B4FEE09CC94CEC77556853F105622AE67466.PNG</Image>
      <Description>Win a fight against an AT-AT walker...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>15</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>You seek Yoda</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/EDFACC6C682C1AFBC50D193B771EBB064C0BABFA.PNG</Image>
      <Description>Get an award from master Yoda on the...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>16</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Bring balance to...</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/BCC217D9439C6FFAFCAD87B2CE40BFCD4428FF60.PNG</Image>
      <Description>Start Jedi and Sith multiballs at the...</Description>
      <Type>SILVER</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>17</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Point Rain</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/AC45C10470945763FB74954A6859CE84B0932CE9.PNG</Image>
      <Description>Transport at least 3 clone troopers...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>18</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>The General</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/31C0DBB41A7521EF3955F175E496BA1862AED443.PNG</Image>
      <Description>Earn the highest rank by completing...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>19</Id>
      <GameId>NPWR04182_00</GameId>
      <Title>Purge the World</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04182_00_00E31B565DC0939E358BF75E7DCDA7D3C1AE5D67FD/271C2A38B676355E5BDA63E46F6DA75ECDFC6851.PNG</Image>
      <Description>Purge the galaxy by defeating both...</Description>
      <Type>SILVER</Type>
      <Hidden/>
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/_wip/xXREDXIIIXx/NPWR03663_00.xml
<?xml version="1.0" encoding="UTF-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR03663_00</Id>
    <IdEurope/>
    <Title>Dollar Dash</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/F27AB683EA81BA9A54D06B88071388948BF7BF68.PNG</Image>
    <TrophiesCount Total="20" Bronze="19" Silver="1" Gold="0" Platinum="0"/>
    <TotalPoints/>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Thief</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/4785EF8107DDD97AFA1466CCB9A4C504076B1C9E.PNG</Image>
      <Description>Steal $1000 in a single match from other players.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Capo</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/788E47F5CB28DAAD8CADD5CC69DABEBC15EF9E6B.PNG</Image>
      <Description>Acquire rank Capo.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Boss</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/36877EE52CF614D0E66E924760FE58EE14EF0BE1.PNG</Image>
      <Description>Acquire rank Boss.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Fully loaded</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/16F5A2E379BB22ACCA94BE1927A73EE83680E220.PNG</Image>
      <Description>Buy every shop item.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Boulder Dash</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/C9B0750FFF09E40A1F1B5498A24484B0A8BACA8A.PNG</Image>
      <Description>In an online game, hit 3 human players with a single boulder.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Tight Win</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/C818547CB8DDFCC929FF4068044F8DECF7A88D50.PNG</Image>
      <Description>Win an online match with a lead of $100.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Highest Rank</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/CB476CF7D06463C44542154F448927C18C27F03C.PNG</Image>
      <Description>Acquire highest rank.</Description>
      <Type>SILVER</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Homerun</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/17D0407AFE3E02E32C4489ADFC1DF78EFF57DD79.PNG</Image>
      <Description>In an online game, deposit a full bag of $1000 at the getaway car.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Master of Dollar Dash</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/18C49E4C9F215CF0589592C30A3DC2C9C5C22DAC.PNG</Image>
      <Description>Win 5 games or finish 20 games in mode Dollar Dash (online).</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Master of Hit'n'Run</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/573BEA1949A7011B74EC9D5AB561A66EBD8504FE.PNG</Image>
      <Description>Win 5 games or finish 20 games in mode Hit'n'Run (online).</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Master of the Safe!</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/84FE0AF2D106C9E457B8800B77E394527A2A7843.PNG</Image>
      <Description>Win 5 games or finish 20 games in mode Save the Safe (online).</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Untouchable</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/FF8CF8C97C7F228B22D692F9818D946749CBD5AB.PNG</Image>
      <Description>Win one game in Mode Hit'n'Run without beeing knocked out by other players (online).</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>13</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Missile Defense System</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/751310D174F20DE3A7824DBA5592F7807A3840F8.PNG</Image>
      <Description>Bounce a nuke with Jelly.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>14</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Boxer</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/477821704F58E656BB6E9A2DEF11EABFCE9EFDC4.PNG</Image>
      <Description>Knock out an opponent with melee attacks.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>15</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Drunkard</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/38186F3EA2F699F624AA72E96031A18A15EE89AF.PNG</Image>
      <Description>Suffer beer damage 10 times in a single match.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>16</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Inseparable</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/A4CB425E990DD6655EE2FA6F2FB6C7B2E03E22CA.PNG</Image>
      <Description>Win a Save the Safe match without losing the safe (online).</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>17</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Taunted</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/9C1B0C59C6C66F765B0154C9273BA5F1CCD3A0B1.PNG</Image>
      <Description>Use both taunts and win an online match.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>18</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Magpie escape</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/D3C54FA7B49EB12698E1328A3F7A83F2CA077C88.PNG</Image>
      <Description>Outrun a magpie.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>19</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>Customized</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/3DCB380A5CB083D39DE6EF34DF848AF67714645D.PNG</Image>
      <Description>Win an online game with a custom hat, face </Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>20</Id>
      <GameId>NPWR03663_00</GameId>
      <Title>My first robbery</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03663_00_005EB4F85BFD96D2A40159A8DE096B7E14F7C2E9BA/71DC312CF318ACF6E346AB2B9EBEABB6753C5CA2.PNG</Image>
      <Description>Complete the Boot Camp.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
  </Trophies>
</PlayStationGame>
