=== JamesSkemp/PsnTrophies/PlayStationGame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="PlayStationGame">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Game">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Id"/>
							<xs:element name="IdEurope"/>
							<xs:element name="Title"/>
							<xs:element name="Image"/>
							<xs:element name="TrophiesCount">
								<xs:complexType>
									<xs:attribute name="Total" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Bronze" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Silver" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Gold" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Platinum" type="xs:nonNegativeInteger"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalPoints"/>
							<xs:element name="Platform"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Trophies">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="Trophy">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Id"/>
										<xs:element name="GameId"/>
										<xs:element name="Title"/>
										<xs:element name="Image"/>
										<xs:element name="Description"/>
										<xs:element name="Type"/>
										<xs:element name="Hidden" nillable="true" type="xs:boolean">
											<xs:annotation>
												<xs:documentation>Whether the trophy is hidden/secret.</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/PsnTrophies/games/NPWR01706_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR01706_00</Id>
    <IdEurope></IdEurope>
    <Title>Dead Block</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/C6245EC19AFA410EB7C41B2104000B787FD16E88.PNG</Image>
    <TrophiesCount Total="12" Bronze="8" Silver="3" Gold="1" Platinum="0" />
    <TotalPoints>300</TotalPoints>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Jack the Builder</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/F78F04CEFD06073E4DEDB810DDC6615192A66023.PNG</Image>
      <Description>Put blockades on every door and window in one level.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Poo Dance</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/43E641BF01A4303AB537C3702A2570D3E4172345.PNG</Image>
      <Description>Make ten infected zombies dance at the same time.</Description>
      <Type>SILVER</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Nightshift</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/256D8D7E187CEF14A0DD95E9EBEB7433A58B29CA.PNG</Image>
      <Description>Play five minutes in darkness.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>All Traps</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/5471884B3F23685D8D6D5878710797CC15909EC4.PNG</Image>
      <Description>Build every trap and a wood blockade in one level.</Description>
      <Type>SILVER</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Bomber</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/A3575C21AC7309A9CE40803999B2BA9629882A07.PNG</Image>
      <Description>Kill twenty zombies with a single bomb trap.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Work force</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/505368AA8CFFEC6C04DBF68EB056FF4DC828C65F.PNG</Image>
      <Description>Employ 20 construction zombies at the same time.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Dead can Dance</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/29738898819DEBC7D5AED1A26A10641C5925C2FF.PNG</Image>
      <Description>Activate the Jukebox and make a zombie dance.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Cactustime</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/3EC736A6C9E8266B4DD0CFD713937BE440864AA9.PNG</Image>
      <Description>While playing Mike, search four cacti in a row.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Quintupel Super Awesome</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/CC1132F2889B660D4FADDE8DA0352A019F58BB8C.PNG</Image>
      <Description>Build five blockades with super awesome finish in a row.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Multikill</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/751BAC413B891DE156BF22B5433F5EF371582555.PNG</Image>
      <Description>While playing Foxy, kill three zombies with one melee attack.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Game Complete</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/91AE378BEF55F8B449450E5FCF51F08544EA395B.PNG</Image>
      <Description>Complete all singleplayer levels.</Description>
      <Type>SILVER</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR01706_00</GameId>
      <Title>Medal Seeker</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01706_00_01EEAC2B90275E171F41907DB5BB027B2603AE17/BD18362C468A2E875B5E1465D144E41CAE1FC42A.PNG</Image>
      <Description>Win all gold medals in all singleplayer levels.</Description>
      <Type>GOLD</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/games/NPWR03597_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR03597_00</Id>
    <IdEurope></IdEurope>
    <Title>Double Dragon Neon</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/4C7B4CE5428590CD5FD1CDDC9E702FA095BA2A92.PNG</Image>
    <TrophiesCount Total="13" Bronze="9" Silver="3" Gold="1" Platinum="0" />
    <TotalPoints>315</TotalPoints>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>FuzzFace!!</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/DAD0C4E4EB774B7281E8B76AE204649D3DA3E3C2.PNG</Image>
      <Description>Befriend everyone's most favoritest helpful character!</Description>
      <Type>BRONZE</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Metal Head</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/4AFA50C975B74357C0A82BF9F41EC48B53222BB3.PNG</Image>
      <Description>Upgrade a song at the Tapesmith</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Weapon Master</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/73D8CD5691CD840BAD597C3A53A8E2AAA9EFF628.PNG</Image>
      <Description>Use every weapon once</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>A Foot Face?</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/D7B168B03936418497CDE051AEB848EC7A67E8DC.PNG</Image>
      <Description>Become the hidden idol!</Description>
      <Type>BRONZE</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Gleam On!</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/25C4AB2EC5D5B9CAD56600C402053B78EFA9EFE7.PNG</Image>
      <Description>Dodge and get the Gleam 50 times</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Mr. Perfect</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/F17290F28E1141224C4967B7E9A6515D8FB2B459.PNG</Image>
      <Description>Complete any level without taking damage</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>This Channel Sucks</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/8F3A16917F454E8C6392143D23E2BED66C0CB4E8.PNG</Image>
      <Description>Break all the Skullmageddon monitors in the Rocket Dojo</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Pick a Winner!</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/4D03C12E70174C93CA5B89999819CF4672443327.PNG</Image>
      <Description>Nail all enemies with the hair pick</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Victory!</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/26D25261386246C04B8B48B44BB98589D7334ECE.PNG</Image>
      <Description>Defeat Skullmageddon!</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Misters Perfect</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/D0EBE709DDBF2987BBD5D985B7EB55CF694EB165.PNG</Image>
      <Description>Complete any level in co-op without taking any damage... with friendly fire enabled!</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Double Dragon</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/BE81D4DF7AB3F519A1F60FA9F7D69F8A7819DC4B.PNG</Image>
      <Description>Finish every stage cooperatively on Double Dragon difficulty with friendly fire enabled!</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Max Fidelity</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/6F351768AE5D9501E14A3A563338AD17B99B760B.PNG</Image>
      <Description>Max out every song to level 50!!</Description>
      <Type>GOLD</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>13</Id>
      <GameId>NPWR03597_00</GameId>
      <Title>Single Dragon</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03597_00_B4069AB5594A2D943BAFB34D8D0D29C9965AC037/150A82BB0A557186A1B3C7740C26D4BA7E01B77D.PNG</Image>
      <Description>Finish every stage solo on Double Dragon difficulty!</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/games/NPWR01320_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR01320_00</Id>
    <IdEurope></IdEurope>
    <Title>SCOTT PILGRIM VS. THE WORLD: THE GAME</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_016D1DF1690A1AC3CBE4E1C355E3DC554A173FAA31/83228FE7E66BCD07AFD58A28A2FF73ADA1925F27.PNG</Image>
    <TrophiesCount Total="19" Bronze="11" Silver="6" Gold="2" Platinum="0" />
    <TotalPoints>525</TotalPoints>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>New Challenger</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/956AA4246BD3C12F96A860EFD8EA3A4511877713.PNG</Image>
      <Description>Defeat Matthew Patel without losing a life.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Twin Dragons</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/2844D652E3A00913BA778CAD76A2816E530FA667.PNG</Image>
      <Description>Defeat the Twins simultaneously.</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Dirty Trick</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/3212D02F61269BB4E7BB9724D7470D95FCFCFA67.PNG</Image>
      <Description>Defeat an enemy by throwing an object at him while he’s already down.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Invulnerable</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/7F7DA25A92C489AA305E802627EF2C56E66681B8.PNG</Image>
      <Description>Play through a World and reach the boss without getting hit.</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Get The Girl</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/601B220B8B7A6C17898E0B64B31CD121544ACA33.PNG</Image>
      <Description>Clear the game once with Scott.</Description>
      <Type>GOLD</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>The Power Of Friendship</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/3F319F5426404C6469C84D57B1F7B9B0ECD2A29A.PNG</Image>
      <Description>In a multiplayer game, reanimate another player at least 25 times.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Gourmet</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/29C747FDCB682A00F286F928E9A6B6B3561E1CBB.PNG</Image>
      <Description>Eat every food items.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Vigilante</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/8712224C85789AF720C08D1D2594C474A85F7331.PNG</Image>
      <Description>Defeat 1000 enemies.</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>One Man Army</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/CD5E2F13F8BB551255C50DA0282E157BF8440EFE.PNG</Image>
      <Description>Clear the game in single player on the “Supreme Master” difficulty setting.</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Shopaholic</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/AFEBBCCF76B006DA3E255CACEA8F2F31F0E8BC1D.PNG</Image>
      <Description>Buy all the items of a shop during the same visit.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Armed And Dangerous</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/2B4C74B031E63C6C126EFE7C4656032196656862.PNG</Image>
      <Description>Defeat at least 200 enemies using interactive objects.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>“Chaudown”</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/A330F924EFCFED8F0B86C22312ECBFAA2FC52F99.PNG</Image>
      <Description>Unlock and call all strikers.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>13</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>It’s All In The Reflexes</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/C12CC26EF080790AACAB4255A8CEE7590EADFD9B.PNG</Image>
      <Description>Catch a flying object at least 25 times with Knives.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>14</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Speed Run</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/2CA55E59EB5DA912B1A61103B1ECD3CA0C5F8B95.PNG</Image>
      <Description>Clear the game in 90 minutes or less with Knives.</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>15</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Ninja Somersault</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_99AEBDAD64F168E03AAB052300041E4C358A654C/E6EE45889D57FE32582C63BF1C1C48FF6A4CDEE4.PNG</Image>
      <Description>Perform at least 10 consecutive head stomps successfully with Knives.</Description>
      <Type>GOLD</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>16</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Wallace the novice!</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_016D1DF1690A1AC3CBE4E1C355E3DC554A173FAA31/F4B617B316C2210D86D16BB69B8AC8990A96B302.PNG</Image>
      <Description>Completed your first online match with Scott Pilgrim Online Multiplayer and Wallace pack</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>17</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Everybody wants to play</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_016D1DF1690A1AC3CBE4E1C355E3DC554A173FAA31/07BA75715F7D9E9329A1877157BEE542C352E7A4.PNG</Image>
      <Description>Played Online with all characters at least once (including Wallace Wells)</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>18</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>And… It’s a Wrap!</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_016D1DF1690A1AC3CBE4E1C355E3DC554A173FAA31/9CC2DF73E1B9EF81D7AFEA4986F2EB4807CA9658.PNG</Image>
      <Description>Clear the game once with Wallace Wells</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>19</Id>
      <GameId>NPWR01320_00</GameId>
      <Title>Wallaciraptor!</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01320_00_016D1DF1690A1AC3CBE4E1C355E3DC554A173FAA31/2A6701B2115854420BB75207420DA1929B5F8888.PNG</Image>
      <Description>Knockout 200 enemies in online mode with Scott Pilgrim Online Multiplayer and Wallace pack</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/_wip/xXREDXIIIXx/NPWR00542_00.xml
<?xml version="1.0" encoding="UTF-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR00542_00</Id>
    <IdEurope/>
    <Title>Flower</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/E2F2D3A0C9F0E1F4A987BA182CAE002321C4DFB8.PNG</Image>
    <TrophiesCount Total="14" Bronze="11" Silver="2" Gold="1" Platinum="0"/>
    <TotalPoints/>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Dream</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/60483DA63FFC638566139ACC33B7A62C450AE729.PNG</Image>
      <Description>Beyond all flowers lies another room.</Description>
      <Type>GOLD</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Nature</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/DE9B4FDC9A0617BDD6B141C0D2FDA330E7A2E9C7.PNG</Image>
      <Description>Bloom 10,000 flowers.</Description>
      <Type>SILVER</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Urban</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/470BEFC1BB53F19DFA6317ADC565452835D7E62C.PNG</Image>
      <Description>Completely awaken the city.</Description>
      <Type>SILVER</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Memories</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/E205603A3A2E42949114E5982ADCBC16294FEA0B.PNG</Image>
      <Description>Reminisce for three minutes before returning to the room.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Palette</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/621F41B996C40C06FD95150D3E527431A685E113.PNG</Image>
      <Description>Use the grass as your canvas and paint the ground with three different colors.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Wind</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/276E91DF59E959707315F99890C2E09F52482461.PNG</Image>
      <Description>Play with the windmills and ride the wind seven times.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Illumination</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/2CDD6F77E5B4CC5A695DE571A333D64BCF71CEFA.PNG</Image>
      <Description>Light a darkened pool.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Pure</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/26B51B5328EC6126385E7A7A6C115AFD2BB65890.PNG</Image>
      <Description>Journey to the city unscathed.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Stars</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/6BC722E8367ABB32EF4DDB4C10957A9E560F86C9.PNG</Image>
      <Description>Release all of the names to the sky.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>flOw</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/9A26318DF6295A54EC3B0A5583B6DBCC1F40D582.PNG</Image>
      <Description>Life could be simple...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Welcome Back</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/41D8489191A900F1F25A1FF48A7A2FCD55113DF3.PNG</Image>
      <Description>Play the game after a week long break.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Healthy Play</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/FC424AE5901C220DAE31862D80A4B994D8CAB50E.PNG</Image>
      <Description>Take a ten minute break between any dreams.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>13</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Beginning</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/B9FE3F988FF281AF651C4FD48A0E70A1DEF8D29F.PNG</Image>
      <Description>The dream has just started...</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
    <Trophy>
      <Id>14</Id>
      <GameId>NPWR00542_00</GameId>
      <Title>Discovery</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00542_00_CA7A4EA9068CA36F4AA49810B27B889D503CDB0B/F7750FD77567D4875EC2716A6BC7984AF75D40F8.PNG</Image>
      <Description>Find and bloom a secret flower.</Description>
      <Type>BRONZE</Type>
      <Hidden/>
    </Trophy>
  </Trophies>
</PlayStationGame>
