=== JamesSkemp/PsnTrophies/PlayStationGame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="PlayStationGame">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Game">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Id"/>
							<xs:element name="IdEurope"/>
							<xs:element name="Title"/>
							<xs:element name="Image"/>
							<xs:element name="TrophiesCount">
								<xs:complexType>
									<xs:attribute name="Total" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Bronze" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Silver" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Gold" type="xs:nonNegativeInteger"/>
									<xs:attribute name="Platinum" type="xs:nonNegativeInteger"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalPoints"/>
							<xs:element name="Platform"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Trophies">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="Trophy">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Id"/>
										<xs:element name="GameId"/>
										<xs:element name="Title"/>
										<xs:element name="Image"/>
										<xs:element name="Description"/>
										<xs:element name="Type"/>
										<xs:element name="Hidden" nillable="true" type="xs:boolean">
											<xs:annotation>
												<xs:documentation>Whether the trophy is hidden/secret.</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/PsnTrophies/games/NPWR00914_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR00914_00</Id>
    <IdEurope></IdEurope>
    <Title>Buzz!™ Junior: Dino Den</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/0E2C429BBAF62CB005157672536D7BC6EA0DCB80.PNG</Image>
    <TrophiesCount Total="11" Bronze="5" Silver="5" Gold="1" Platinum="0" />
    <TotalPoints>315</TotalPoints>
    <Platform>?</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Dinner Time Dino</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/A971794B4E66739AD93A42856B110E0CAB05FCBA.PNG</Image>
      <Description>Eat more than half the steaks in a single player game of All You Can Eat!</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Greedy Dino</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/FCC77574B96DC51AE375541AEFAB9113F3CA1D01.PNG</Image>
      <Description>Eat all the steaks in a single player game of All You Can Eat!</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Catch of the Day</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/15F1C30ED77E8A7BC4C153AF804B148A7ED0258A.PNG</Image>
      <Description>Catch all sizes of fish and win a single player game of Ice Fishing.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Fishing Frenzy</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/A0D237D97D0DED919C2BB1D45821929FFF04AE3E.PNG</Image>
      <Description>Catch more than 340kg of fish in a single player game of Ice Fishing.</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Eat My Dust</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/AFCF6F4D020374D691B5F35F3053D2F7FE4A7B46.PNG</Image>
      <Description>Lap an AI controlled opponent in a single player game of Elastic Racers.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Ace Racer</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/D8BFD35BBCE15AADF3DFF6DB3589BFC989CCC47A.PNG</Image>
      <Description>Win a race without spinning out in a single player game of Elastic Racers.</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Hop, Skip and Dino! </Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/F200AC74293095035F883E1D538FC211B1940D4B.PNG</Image>
      <Description>Win every round in a single player game of River Crossing.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Mother Thumper</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/EE24B6BABB127122DAB42F56DFD37788A586C086.PNG</Image>
      <Description>Hit 4 stalactites in a row with the highest power smash in a single player game of River Crossing.</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Easy Rider</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/7EAC9B4D387DE70AD667B922B69F1C63D7AB61CF.PNG</Image>
      <Description>Win a single player game of Hitch A Ride!</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>T-Rex Rambler </Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/7676F46C6B1BE5A19CB750B54D7EFB357DF6CA10.PNG</Image>
      <Description>Never fall off and win a single player game of Hitch A Ride!</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR00914_00</GameId>
      <Title>Prehistoric Perfectionist</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00914_00_00E6B88EFF9FA0F7F2AE4B9848873FC73ABAD5912E/2CA7ED522440AE30D6B031BE436F231EEB4998CA.PNG</Image>
      <Description>Win a standard single player game with the difficulty level set to hard.</Description>
      <Type>GOLD</Type>
      <Hidden>false</Hidden>
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/games/NPWR03869_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR03869_00</Id>
    <IdEurope></IdEurope>
    <Title>Sonic the Fighters</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/89B6C30FAD097AD1649ADA3773733366E24ABF95.PNG</Image>
    <TrophiesCount Total="12" Bronze="7" Silver="4" Gold="1" Platinum="0" />
    <TotalPoints>315</TotalPoints>
    <Platform>?</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Stage 1 Complete</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/7A94A72C90F0A91DEED2F29B0A82EC3841B081F1.PNG</Image>
      <Description>Complete Stage 1 of Arcade Mode (any difficulty)</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Stage 2 Complete</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/1D4790FACD55D205521CF76B889A7FC550C5454B.PNG</Image>
      <Description>Complete Stage 2 of Arcade Mode (any difficulty)</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Stage 3 Complete</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/D4332866DFF26CD45CF967E449AFC3C27DE987D2.PNG</Image>
      <Description>Complete Stage 3 of Arcade Mode (any difficulty)</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Stage 4 Complete</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/6CCED5F2FFBDDF8B194AE44DB03DD7D38BA407D3.PNG</Image>
      <Description>Complete Stage 4 of Arcade Mode (any difficulty)</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Stage 5 Complete</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/49F68D9091B4283FCFFD9AAE61DDA2DDC5C04125.PNG</Image>
      <Description>Complete Stage 5 of Arcade Mode (any difficulty)</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Stage 6 Complete</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/EE05BA7982150E1CEC5C8AF0FFAD4F12DB3CAC45.PNG</Image>
      <Description>Complete Stage 6 of Arcade Mode (any difficulty)</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Stage 7 Complete</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/37E1410006510055F36ABD1BFB2E92ED5D316B03.PNG</Image>
      <Description>Complete Stage 7 of Arcade Mode (any difficulty)</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Perfect</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/0935AC9D267B17E3D1FBF6F2C13659EF5C1DD4A0.PNG</Image>
      <Description>Win a round without receiving any damage in Arcade Mode (any difficulty)</Description>
      <Type>GOLD</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Barrier Destroyer</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/5C1BEC8A6800F46A18491082A24D4BC18F4E6B7F.PNG</Image>
      <Description>Destroy all of an opponent's barriers while playing Arcade Mode or Offline Versus</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>A Small Transformation</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/E51249F2DDE6DE62484CF9F977964EC141D2B4E7.PNG</Image>
      <Description>Turn small by being attacked (ie, by Amy's↓+P, etc) in Arcade Mode or Offline Versus</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>Honey the Cat</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/F41252BF67377E3D57842E26D30DE2F69598D6E1.PNG</Image>
      <Description>Use Honey the Cat in Arcade Mode or Offline Versus (Press START button on Amy and select)</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR03869_00</GameId>
      <Title>The Enemy Within</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR03869_00_00BA8F41D091EFF291A1783EE89777E0AE68637ABA/3CBB98BFACECD474F678897A1AD09A9DC63A917D.PNG</Image>
      <Description>Fight a mirror match in Arcade Mode or Offline Versus</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/games/NPWR04102_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR04102_00</Id>
    <IdEurope></IdEurope>
    <Title>Kingdom Hearts 358/2 Days</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04102_00_00D82C1B1FEC8BAAB25F05CDD553856264EEF23E2C/B31BA073CB786C493D51E6A01ADF5EC36303C40C.PNG</Image>
    <TrophiesCount Total="6" Bronze="3" Silver="0" Gold="3" Platinum="0" />
    <TotalPoints>315</TotalPoints>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR04102_00</GameId>
      <Title>358/2Days コンプリート</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04102_00_00D82C1B1FEC8BAAB25F05CDD553856264EEF23E2C/EAE9CEEF1C951CEFA696E4BF0A836A934FED15B3.PNG</Image>
      <Description>全てのトロフィーを取得した</Description>
      <Type>GOLD</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR04102_00</GameId>
      <Title>リードオールザダイアリー</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04102_00_00D82C1B1FEC8BAAB25F05CDD553856264EEF23E2C/CDAAD91281AEBCD1C6DDCD7EB9D2DDD1E4F49894.PNG</Image>
      <Description>全てのロクサスダイアリーを見た</Description>
      <Type>GOLD</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR04102_00</GameId>
      <Title>リードオールザレポート</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04102_00_00D82C1B1FEC8BAAB25F05CDD553856264EEF23E2C/4D9E52214CC8E3FC3689C15D3BFE9D0A2FDB3449.PNG</Image>
      <Description>全てのシークレットレポートを見た</Description>
      <Type>GOLD</Type>
      <Hidden>true</Hidden>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR04102_00</GameId>
      <Title>Days of Connection</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04102_00_00D82C1B1FEC8BAAB25F05CDD553856264EEF23E2C/83BBE78D40E094BCA818C25E9941BB25A21F7F21.PNG</Image>
      <Description>View Chapters 1 through 37.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR04102_00</GameId>
      <Title>Days of Reflection</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04102_00_00D82C1B1FEC8BAAB25F05CDD553856264EEF23E2C/4DB2BB48DD7FF379CF22C4B9965BA8E57E620E1A.PNG</Image>
      <Description>View Chapters 38 through 74.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR04102_00</GameId>
      <Title>Where the Heart Lies</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR04102_00_00D82C1B1FEC8BAAB25F05CDD553856264EEF23E2C/E5CB4EF88704342AD6039A5C83C39165FDDF19E5.PNG</Image>
      <Description>View Chapters 75 through 109.</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/games/NPWR00106_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR00106_00</Id>
    <IdEurope></IdEurope>
    <Title>Wheel of Fortune</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/3E6755A21F6C3FB3A445A1838A227B1841534A19.PNG</Image>
    <TrophiesCount Total="13" Bronze="9" Silver="3" Gold="1" Platinum="0" />
    <TotalPoints>315</TotalPoints>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Wheel Barrel of Fortune</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/800B6266CA4146D01BEB955E20C2AF7141950727.PNG</Image>
      <Description>$100,000 total winnings</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Wheel of Fortune 500</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/89787F68F17D11A733FF27327FAA87EAD8A2D400.PNG</Image>
      <Description>$500,000 total winnings</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Inventor of the Wheel</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/BACA9C6EFB023494CD9C33BBE6EAC993D149FF25.PNG</Image>
      <Description>$1,000,000 total winnings</Description>
      <Type>GOLD</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Wheely Wheely Good</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/E55715735343C2521FB303232EB3C3BE2DF36372.PNG</Image>
      <Description>$50,000 winnings in one game</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Wheel Around the World</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/6F3F8D0912395FFD7E269562CB7A0E355D24E5CE.PNG</Image>
      <Description>Win an online game</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Lucky Letter</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/5E7DC450238AC7BED60D9C073AB77203F3A5C935.PNG</Image>
      <Description>Correctly select Q, X, or Z in a puzzle</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Ding Ding Ding Ding</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/E3896CA1E9C266BBCB0EE12B0980F9776A2AD224.PNG</Image>
      <Description>Pick a letter that shows up 4 or more times in a puzzle</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Puzzle Apprentice</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/FF9A66F8CC7914546EF6F3DB495F062CB75F5D9F.PNG</Image>
      <Description>Win 10 games</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Puzzle Master</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/B4D5877E1D251773C2F2D349E4E89CD1FC378755.PNG</Image>
      <Description>Win 25 games</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Wheel Consistent</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/96B3A513646A813CB6D660459FA6C1C241198EB7.PNG</Image>
      <Description>Pick 5 letters in a row in one puzzle</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Road Warrior</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/0EEA72C223091BE1C49A09DCE732C10E556F1CD5.PNG</Image>
      <Description>Visit all cities in Road Trip mode</Description>
      <Type>SILVER</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Wheel Spinner</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/565195C9F2852F774CF0A17DD64B0448153A4543.PNG</Image>
      <Description>Win a round</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
    <Trophy>
      <Id>13</Id>
      <GameId>NPWR00106_00</GameId>
      <Title>Wheel Winner</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR00106_00_9527273DF39454FDBDB43B4640F5A7DB4A1AF364/D3F39F8A158D0C072E1DF24C2DECF13D10738A8C.PNG</Image>
      <Description>Win a local game</Description>
      <Type>BRONZE</Type>
      <Hidden>false</Hidden>
    </Trophy>
  </Trophies>
</PlayStationGame>

=== JamesSkemp/PsnTrophies/games/NPWR01080_00.xml
<?xml version="1.0" encoding="utf-8"?>
<PlayStationGame xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PlayStationGame.xsd">
  <Game>
    <Id>NPWR01080_00</Id>
    <IdEurope></IdEurope>
    <Title>Top Gun</Title>
    <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/EBC8C3F30A8AA0BF352E93D8176453CB254C1068.PNG</Image>
    <TrophiesCount Total="12" Bronze="8" Silver="3" Gold="1" Platinum="0" />
    <TotalPoints>300</TotalPoints>
    <Platform>ps3</Platform>
  </Game>
  <Trophies>
    <Trophy>
      <Id>1</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>I feel the need...</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/FFDDD06AA22331ED61032FBF903C6BD0C34534DD.PNG</Image>
      <Description>Awarded after 3 afterburner boosts.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>2</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>Gutsiest move I ever saw..</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/BDA4C3E3F56A7BB9AFFA9031819B0B32F2E708AD.PNG</Image>
      <Description>First plane locked onto with missiles when in CFI and then successfully killed.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>3</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>Jester’s Dead</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/033747C2667AE2E230793FB5829B0518271D9113.PNG</Image>
      <Description>Jester is shot down at any point by either you or your wingman.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>4</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>Close But No Cigar</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/3E3862B83845EB0E8023D5C1C26CA9E63E12B8ED.PNG</Image>
      <Description>Mission 4 (1st playthrough – Viper wins).</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>5</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>Top Gun</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/A2C16863E3B827639F637A66D4E991F2ED0E8361.PNG</Image>
      <Description>Mission 4 (2nd playthrough – Player wins).</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>6</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>You can be my wingman anytime...</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/14224966B1D6902C06393848CE339C88768FA98E.PNG</Image>
      <Description>Complete all the Indian Ocean Missions.</Description>
      <Type>SILVER</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>7</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>The Pattern is Full</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/9758302FA27E6467637055F280496043F8BDB6ED.PNG</Image>
      <Description>Complete all of Prologue, Top Gun Academy and Indian Ocean with all planes (any difficulty).</Description>
      <Type>GOLD</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>8</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>You’re Dangerous</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/68CAE6F40F770D964EEBCDD6007F30685B06A20C.PNG</Image>
      <Description>Complete any one of three hidden flight runs.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>9</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>That’s Right, I am Dangerous</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/DB112C82C00DD924B095824071686CB756A4B57A.PNG</Image>
      <Description>Complete all 3 of the hidden runs.</Description>
      <Type>SILVER</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>10</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>Target Rich Environment</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/F6980485DE5B91D276F9762F3B8C3265FF511374.PNG</Image>
      <Description>99 kills in Multiplayer (with Missiles or Guns).</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>11</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>Goosed</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/881537095296B55DD3D3D22ECC5116008BCC6BF3.PNG</Image>
      <Description>Rewarded for more than 10 gratuitous deaths in a single multiplayer match.</Description>
      <Type>BRONZE</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
    <Trophy>
      <Id>12</Id>
      <GameId>NPWR01080_00</GameId>
      <Title>No Points For Second Place</Title>
      <Image>http://trophy01.np.community.playstation.net/trophy/np/NPWR01080_00_873D1E036E092F1B8321D1825B8B902D8AC2FA49/18C620CD237E9A5DE0413341E7CBBB6EF16227B0.PNG</Image>
      <Description>Be the first to get the star in a multiplayer match, and hold on to it until the bitter end.</Description>
      <Type>SILVER</Type>
      <Hidden xsi:nil="true" />
    </Trophy>
  </Trophies>
</PlayStationGame>
